#include <iostream>
using namespace std;
int main(){
    
    int n;
    cout<<"Enter The Value Of N:-";
    cin>>n;
    if(n%2==0)
      cout<<"Even number";
    if(n%2!=0)
      cout<<"Odd Number";
}    
    
    
    
    
    
    
    
// #include <iostream>
// using namespace std;
// int main(){
  
//   int n;
//   cout<<"Enter The Value Of N:-";
//   cin>>n;
//   if(n%2==0) {
//     cout<<"Even Number";
//   } 
//   else { 
//       cout<<"Odd Number"<<endl;
//       cout<<"THAT NICE"
//   }
//}